#ifndef _DEFINICIONES_H
#define _DEFINICIONES_H

#define LARGO 100
#define CANTIDAD_CAJEROS 3
#define INTERVALO_CHEQUEO 100
#define MAXIMA_CANTIDAD_PRODUCTOS_CAJERO_1 5
#define MAXIMA_CANTIDAD_PRODUCTOS_CAJERO_2 10
#define LARGO_ARREGLO_PRODUCTOS 100
#define LARGO_NOMBRE_PRODUCTO 50

#endif
